version: '3'
services:
  web:
    image: mvlat/web
    restart: always
    volumes:
      - ${VOLUMES}/web:/usr/share/nginx/html/assets
    expose:
      - "80"
    ports:
      - "${IP}:80:80"
    environment:
      - VIRTUAL_HOST=www.${DOMAIN}
      - VIRTUAL_PORT=80

  rest:
    image: mvlat/rest
    restart: always
    volumes:
      - "${VOLUMES}/rest:/rest-data"
    expose:
      - "7301"
    ports:
      - "${IP}:7301:7301"
    environment:
      - VIRTUAL_HOST=rest.${DOMAIN}
      - VIRTUAL_PORT=7301

  assets:
    image: mvlat/assets
    restart: always
    volumes:
      - ${VOLUMES}/assets:/assets-data
    expose:
      - "7302"
    ports:
      - "${IP}:7302:7302"
    environment:
      - VIRTUAL_HOST=assets.${DOMAIN}
      - VIRTUAL_PORT=7302

  calendar:
    image: mvlat/calendar
    restart: always
    volumes:
      - ${VOLUMES}/calendar:/calendar-data
    expose:
      - "7303"
    ports:
      - "${IP}:7303:7303"
    environment:
      - VIRTUAL_HOST=calendar.${DOMAIN}
      - VIRTUAL_PORT=7303

  sync:
    image: gici/git-sync
    restart: always
    volumes:
      - ${VOLUMES}/library:/git
    environment:
      - GIT_SYNC_REPO=https://github.com/mvl-at/library.git
      - GIT_SYNC_DEST=/git
      - GIT_SYNC_BRANCH=master
      - GIT_SYNC_REV=FETCH_HEAD
      - GIT_SYNC_WAIT=10

  library:
    image: klakegg/hugo:asciidoctor
    restart: always
    command: server
    depends_on:
      - sync
    volumes:
      - ${VOLUMES}/library:/src
    expose:
      - "1313"
    ports:
      - "${IP}:1313:1313"
    environment:
      - VIRTUAL_HOST=library.${DOMAIN}
      - VIRTUAL_PORT=1313

  nginx-web:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${NGINX_WEB:-nginx-web}
    restart: always
    ports:
      - "${IP:-0.0.0.0}:80:80"
      - "${IP:-0.0.0.0}:443:443"
    volumes:
      - ${VOLUMES}/${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${VOLUMES}/${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${VOLUMES}/${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${VOLUMES}/${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${VOLUMES}/${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      options:
        max-size: ${NGINX_WEB_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_WEB_LOG_MAX_FILE:-10}

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup ${NGINX_WEB:-nginx-web} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN:-nginx-gen}
    restart: always
    volumes:
      - ${VOLUMES}/${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${VOLUMES}/${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${VOLUMES}/${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${VOLUMES}/${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${VOLUMES}/${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      options:
        max-size: ${NGINX_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_GEN_LOG_MAX_FILE:-10}

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${LETS_ENCRYPT:-nginx-letsencrypt}
    restart: always
    volumes:
      - ${VOLUMES}/${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${VOLUMES}/${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${VOLUMES}/${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${VOLUMES}/${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN:-nginx-gen}
      NGINX_PROXY_CONTAINER: ${NGINX_WEB:-nginx-web}
    logging:
      options:
        max-size: ${NGINX_LETSENCRYPT_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_LETSENCRYPT_LOG_MAX_FILE:-10}
